In [1]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv('cleardataset/premier-league-matches.csv')

conditions = [
    df['HomeGoals'] == df['AwayGoals'],                         # 무승부
    (df['FTR'] == 'H') & (df['HomeGoals'] > df['AwayGoals']),   # 홈 승
    (df['FTR'] == 'A') & (df['AwayGoals'] > df['HomeGoals'])    # 원정 승
]

# 각 조건에 대응하는 값
choices = [1, 3, 3]

# 조건을 만족하지 않는 경우(패배)는 0
df['Points'] = np.select(conditions, choices, default=0)

# --- 3) Points 기준 정렬(내림차순) ---
df = df.sort_values(by='Points', ascending=False)

print(df)

      Season_End_Year  Wk        Date           Home  HomeGoals  AwayGoals  \
0                1993   1  1992-08-15  Coventry City          2          1
7460             2011  38  2011-05-22      Tottenham          2          1
7493             2012   3  2011-08-28      West Brom          0          1
7494             2012   3  2011-08-28  Newcastle Utd          2          1
7496             2012   4  2011-09-10         Bolton          0          5
...               ...  ..         ...            ...        ...        ...
4245             2003  21  2002-12-28        Everton          0          0
8282             2014   6  2013-09-28      Tottenham          1          1
6411             2009   9  2008-10-26     Portsmouth          1          1
1715             1996  34  1996-04-06       West Ham          1          1
7601             2012  14  2011-12-03            QPR          1          1

                 Away FTR  Points
0       Middlesbrough   H       3
7460  Birmingham City   H       3
7493       Stoke City   A       3
7494           Fulham   H       3
7496   Manchester Utd   A       3
...               ...  ..     ...
4245           Bolton   D       1
8282          Chelsea   D       1
6411           Fulham   D       1
1715        Wimbledon   D       1
7601        West Brom   D       1

[12026 rows x 9 columns]

In [5]:
output_path = 'dataset/results_with_points.csv' 
df.to_csv(output_path, index=False, encoding='utf-8-sig')

In [19]:
# 2) 홈/원정 각각 승점 계산 ──────────────────────────
def points_per_side(row):
    if row['HomeGoals'] > row['AwayGoals']:      # 홈 승
        return pd.Series({'HomePts': 3, 'AwayPts': 0})
    elif row['HomeGoals'] < row['AwayGoals']:    # 원정 승
        return pd.Series({'HomePts': 0, 'AwayPts': 3})
    else:                                        # 무승부
        return pd.Series({'HomePts': 1, 'AwayPts': 1})

df[['HomePts', 'AwayPts']] = df.apply(points_per_side, axis=1)

# 3) 홈·원정 정보를 하나로 묶어 팀‑시즌별로 집계 ────────
home = (
    df[['Season_End_Year', 'Home', 'HomePts']]
      .rename(columns={'Home': 'Team', 'HomePts': 'Points'})
)
away = (
    df[['Season_End_Year', 'Away', 'AwayPts']]
      .rename(columns={'Away': 'Team', 'AwayPts': 'Points'})
)

points_long = pd.concat([home, away], ignore_index=True)

team_season_pts = (
    points_long
      .groupby(['Team', 'Season_End_Year'], as_index=False)['Points']
      .sum()
)

# 4) 피벗: 행=Team, 열=Season_end_year ────────────────
pivot = (
    team_season_pts
      .pivot(index='Team', columns='Season_End_Year', values='Points')
)

# 5) 빠진 시즌(열) 0으로 채우고 정렬 ───────────────────
all_seasons = list(range(1992, 2026))            # 1992 ~ 2025

pivot = (
    pivot
      .reindex(columns=all_seasons)   
      .fillna(0)                      
      .astype(int)                    
      .sort_index(axis=1)             
      .sort_index()                   
)

print(pivot)
pivot.to_csv('dataset/season_points_by_team.csv')

Season_End_Year  1992  1993  1994  1995  1996  1997  1998  1999  2000  2001  \
Team
Arsenal             0    56    71    51    63    68    78    78    73    70
Aston Villa         0    74    57    48    63    61    57    55    58    54
Barnsley            0     0     0     0     0     0    35     0     0     0
Birmingham City     0     0     0     0     0     0     0     0     0     0
Blackburn           0    71    84    89    61    42    58    35     0     0
Blackpool           0     0     0     0     0     0     0     0     0     0
Bolton              0     0     0     0    29     0    40     0     0     0
Bournemouth         0     0     0     0     0     0     0     0     0     0
Bradford City       0     0     0     0     0     0     0     0    36    26
Brentford           0     0     0     0     0     0     0     0     0     0
Brighton            0     0     0     0     0     0     0     0     0     0
Burnley             0     0     0     0     0     0     0     0     0     0
Cardiff City        0     0     0     0     0     0     0     0     0     0
Charlton Ath        0     0     0     0     0     0     0    36     0    52
Chelsea             0    56    51    54    50    59    63    75    65    61
Coventry City       0    52    56    50    38    41    52    42    44    34
Crystal Palace      0    49     0    45     0     0    33     0     0     0
Derby County        0     0     0     0     0    46    55    52    38    42
Everton             0    53    44    50    61    42    40    43    50    42
Fulham              0     0     0     0     0     0     0     0     0     0
Huddersfield        0     0     0     0     0     0     0     0     0     0
Hull City           0     0     0     0     0     0     0     0     0     0
Ipswich Town        0    52    43    27     0     0     0     0     0    66
Leeds United        0    51    70    73    43    46    59    67    69    68
Leicester City      0     0     0    29     0    47    53    49    55    48
Liverpool           0    59    60    74    71    68    65    54    67    69
Manchester City     0    57    45    49    38     0     0     0     0    34
Manchester Utd      0    84    92    88    82    75    77    79    91    80
Middlesbrough       0    44     0     0    43    42     0    51    52    42
Newcastle Utd       0     0    77    72    78    68    44    46    52    51
Norwich City        0    72    53    43     0     0     0     0     0     0
Nott'ham Forest     0    40     0    77    58    34     0    30     0     0
Oldham Athletic     0    49    40     0     0     0     0     0     0     0
Portsmouth          0     0     0     0     0     0     0     0     0     0
QPR                 0    63    60    60    33     0     0     0     0     0
Reading             0     0     0     0     0     0     0     0     0     0
Sheffield Utd       0    52    42     0     0     0     0     0     0     0
Sheffield Weds      0    59    64    51    40    57    44    46    31     0
Southampton         0    50    43    54    38    41    48    41    44    52
Stoke City          0     0     0     0     0     0     0     0     0     0
Sunderland          0     0     0     0     0    40     0     0    58    57
Swansea City        0     0     0     0     0     0     0     0     0     0
Swindon Town        0     0    30     0     0     0     0     0     0     0
Tottenham           0    59    45    62    61    46    44    47    53    49
Watford             0     0     0     0     0     0     0     0    24     0
West Brom           0     0     0     0     0     0     0     0     0     0
West Ham            0     0    52    50    51    42    56    57    55    42
Wigan Athletic      0     0     0     0     0     0     0     0     0     0
Wimbledon           0    54    65    56    41    56    44    42    33     0
Wolves              0     0     0     0     0     0     0     0     0     0

Season_End_Year  ...  2016  2017  2018  2019  2020  2021  2022  2023  2024  \
Team             ...
Arsenal          ...    71    75    63    70    56    61    69    84     0
Aston Villa      ...    17     0     0     0    35    55    45    61     0
Barnsley         ...     0     0     0     0     0     0     0     0     0
Birmingham City  ...     0     0     0     0     0     0     0     0     0
Blackburn        ...     0     0     0     0     0     0     0     0     0
Blackpool        ...     0     0     0     0     0     0     0     0     0
Bolton           ...     0     0     0     0     0     0     0     0     0
Bournemouth      ...    42    46    44    45    34     0     0    39     0
Bradford City    ...     0     0     0     0     0     0     0     0     0
Brentford        ...     0     0     0     0     0     0    46    59     0
Brighton         ...     0     0    40    36    41    41    51    62     0
Burnley          ...     0    40    54    40    54    39    35     0     0
Cardiff City     ...     0     0     0    34     0     0     0     0     0
Charlton Ath     ...     0     0     0     0     0     0     0     0     0
Chelsea          ...    50    93    70    72    66    67    74    44     0
Coventry City    ...     0     0     0     0     0     0     0     0     0
Crystal Palace   ...    42    41    44    49    43    44    48    45     0
Derby County     ...     0     0     0     0     0     0     0     0     0
Everton          ...    47    61    49    54    49    59    39    36     0
Fulham           ...     0     0     0    26     0    28     0    52     0
Huddersfield     ...     0     0    37    16     0     0     0     0     0
Hull City        ...     0    34     0     0     0     0     0     0     0
Ipswich Town     ...     0     0     0     0     0     0     0     0     0
Leeds United     ...     0     0     0     0     0    59    38    31     0
Leicester City   ...    81    44    47    52    62    66    52    34     0
Liverpool        ...    60    76    75    97    99    69    92    67     0
Manchester City  ...    66    78   100    98    81    86    93    89     0
Manchester Utd   ...    66    69    81    66    66    74    58    75     0
Middlesbrough    ...     0    28     0     0     0     0     0     0     0
Newcastle Utd    ...    37     0    44    45    44    45    49    71     0
Norwich City     ...    34     0     0     0    21     0    22     0     0
Nott'ham Forest  ...     0     0     0     0     0     0     0    38     0
Oldham Athletic  ...     0     0     0     0     0     0     0     0     0
Portsmouth       ...     0     0     0     0     0     0     0     0     0
QPR              ...     0     0     0     0     0     0     0     0     0
Reading          ...     0     0     0     0     0     0     0     0     0
Sheffield Utd    ...     0     0     0     0    54    23     0     0     0
Sheffield Weds   ...     0     0     0     0     0     0     0     0     0
Southampton      ...    63    46    36    39    52    43    40    25     0
Stoke City       ...    51    44    33     0     0     0     0     0     0
Sunderland       ...    39    24     0     0     0     0     0     0     0
Swansea City     ...    47    41    33     0     0     0     0     0     0
Swindon Town     ...     0     0     0     0     0     0     0     0     0
Tottenham        ...    70    86    77    71    59    62    71    60     0
Watford          ...    45    40    41    50    34     0    23     0     0
West Brom        ...    43    45    31     0     0    26     0     0     0
West Ham         ...    62    45    42    52    39    65    56    40     0
Wigan Athletic   ...     0     0     0     0     0     0     0     0     0
Wimbledon        ...     0     0     0     0     0     0     0     0     0
Wolves           ...     0     0     0    57    59    45    51    41     0

Season_End_Year  2025
Team
Arsenal             0
Aston Villa         0
Barnsley            0
Birmingham City     0
Blackburn           0
Blackpool           0
Bolton              0
Bournemouth         0
Bradford City       0
Brentford           0
Brighton            0
Burnley             0
Cardiff City        0
Charlton Ath        0
Chelsea             0
Coventry City       0
Crystal Palace      0
Derby County        0
Everton             0
Fulham              0
Huddersfield        0
Hull City           0
Ipswich Town        0
Leeds United        0
Leicester City      0
Liverpool           0
Manchester City     0
Manchester Utd      0
Middlesbrough       0
Newcastle Utd       0
Norwich City        0
Nott'ham Forest     0
Oldham Athletic     0
Portsmouth          0
QPR                 0
Reading             0
Sheffield Utd       0
Sheffield Weds      0
Southampton         0
Stoke City          0
Sunderland          0
Swansea City        0
Swindon Town        0
Tottenham           0
Watford             0
West Brom           0
West Ham            0
Wigan Athletic      0
Wimbledon           0
Wolves              0

[50 rows x 34 columns]

In [20]:
df2 = pd.read_csv('dataset/season_points_by_team.csv')

df2['sum'] = df2.loc[:, '1992':'2025'].sum(axis=1)

top10 = (
    df2.sort_values(by='sum', ascending=False)
       .reset_index()
       .loc[:, ['Team', 'sum']]
       .rename(columns={'Team': '팀 이름', 'sum': '총 승점'})
)

top10.index += 1  # 순위 1부터 시작하도록
print(top10)

               팀 이름  총 승점
1    Manchester Utd  2441
2           Arsenal  2225
3           Chelsea  2182
4         Liverpool  2176
5         Tottenham  1847
6   Manchester City  1718
7           Everton  1610
8     Newcastle Utd  1481
9       Aston Villa  1419
10         West Ham  1298
11      Southampton  1088
12        Blackburn   970
13   Leicester City   821
14     Leeds United   820
15           Fulham   692
16    Middlesbrough   664
17       Sunderland   618
18   Crystal Palace   609
19           Bolton   575
20        West Brom   490
21       Stoke City   457
22    Coventry City   409
23     Norwich City   402
24   Sheffield Weds   392
25        Wimbledon   391
26           Wolves   389
27     Charlton Ath   361
28   Wigan Athletic   331
29          Burnley   325
30     Swansea City   312
31              QPR   308
32       Portsmouth   302
33  Birmingham City   301
34          Watford   285
35  Nott'ham Forest   277
36     Derby County   274
37         Brighton   271
38      Bournemouth   250
39     Ipswich Town   224
40    Sheffield Utd   209
41        Hull City   171
42          Reading   119
43        Brentford   105
44  Oldham Athletic    89
45     Cardiff City    64
46    Bradford City    62
47     Huddersfield    53
48        Blackpool    39
49         Barnsley    35
50     Swindon Town    30